/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoresRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/stores': typeof StoresRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/stores': typeof StoresRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contribute': typeof ContributeRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/stores': typeof StoresRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contribute'
    | '/list'
    | '/login'
    | '/plan'
    | '/stores'
    | '/products/$id'
    | '/stores/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contribute'
    | '/list'
    | '/login'
    | '/plan'
    | '/stores'
    | '/products/$id'
    | '/stores/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/contribute'
    | '/list'
    | '/login'
    | '/plan'
    | '/stores'
    | '/products/$id'
    | '/stores/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributeRoute: typeof ContributeRoute
  ListRoute: typeof ListRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  StoresRoute: typeof StoresRouteWithChildren
  ProductsIdRoute: typeof ProductsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof StoresRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoresRouteChildren {
  StoresIdRoute: typeof StoresIdRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresIdRoute: StoresIdRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributeRoute: ContributeRoute,
  ListRoute: ListRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  StoresRoute: StoresRouteWithChildren,
  ProductsIdRoute: ProductsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
